server {
    gzip on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    listen  82;
    server_name  cameliya.cn www.cameliya.cn;
    location / {
      root /app/docs-dist;
      try_files $uri $uri/   /index.html;
      add_header Cache-Control "no-cache, no-store";
      index  index.html index.htm;
    }
  }
